USB: fix undeclared hub_release error in x86 build
drivers/usb/core/hub.c: In function 'hub_activate':
drivers/usb/core/hub.c:1001:25: error: 'hub_release' undeclared (first use in this function)
    kref_put(&hub->kref, hub_release);

Change-Id: I94e829a7ac7c53027638b8093883dad02ac353c1

(cherry picked from commit ed0b9b4e69b8beaa6bd3da338fa5a31cc0c3db2a)
(cherry picked from commit 90c3b113c6654579de72452d9fc61a26c58c6ad3)