sched: cpufreq: update power usage only if cpufreq_stat is enabled
Call acct_update_power() to track power usage of task only if
CONFIG_CPU_FREQ_STAT is enabled, otherwise we run into
following build failure:
---------------
kernel/built-in.o: In function `account_user_time':
kernel/sched/cputime.c:155: undefined reference to `acct_update_power'
kernel/built-in.o: In function `__account_system_time':
kernel/sched/cputime.c:208: undefined reference to `acct_update_power'
make: *** [vmlinux] Error 1
---------------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

(cherry picked from commit 5371356ed838799125b1379fa38cdddfd1d189fd)

Change-Id: I8dc4ead3ed806fb6ff0ff54e4056ba749bd9b781
(cherry picked from commit ab34cddaf6135f3a5119b9404552367744eb60aa)